source 'https://rubygems.org'

gem 'awesome_print'
gem 'aws-sdk-ec2'
gem 'dotenv'
gem 'gitlab'
gem 'json'
gem 'minitest'
gem 'minitest-reporters'
gem 'octokit', '~> 4.0'
gem 'rerun'
gem 'sequel'
gem 'sinatra'
gem 'sqlite3'
gem 'telegram-bot-ruby'
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
