target: 'amazon'
aws_region: 'us-west-2'
# aws_access_key_id: 'AKIAJQ6NBNKPQ57QZGXA'
aws_access_key_id: 'AKIAJYMX5564SQMSIZOQ'
second_aws_access_key_id: 'AKIAIWIQ4XNSUHGHQ5KA'
wrong_aws_access_key_id: '3CNBFAAKGA577DSWQ'
# aws_secret_access_key: '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'
aws_secret_access_key: 'cim8qC7tsCUC8X4SWjaA6Scv2l6a9Li628/QWpIH'
second_aws_secret_access_key: 'VLZ/RmhsV5n0DLYGPT1xMjxARI3cJZAWhQ+QVHUk'
wrong_aws_secret_access_key: 'WKGkN06vN/eh5/Cdx0rDrUpL54eVmW1zbHRp/Oec'
telegram_api_token: '281376742:AAGOrZsq0q1VyboxE2I-2Ra93yyi7BduRag'
second_telegram_api_token: '520409507:AAGHk9YwklCT4UzJqXJ5nKZkm56ujFsuNJ4'
wrong_telegram_api_token: 'boxE2I-2Ra93yyi7BduRag281376742:AAGOrZsq0q1Vy'
